name: track_linearization
channels:
- defaults
- conda-forge
dependencies:
- "python>=3.10"
- numpy
- scipy
- matplotlib
- pandas
- networkx
- numba
- dask
- ipympl
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pytest
- pytest-cov
- coveralls
